org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.2
java_version=25
mod_version=0.1.0-SNAPSHOT
mod_group=dev.kyresn
mod_id=mc_reflex_tools
mod_name=MC Reflex Tools

fabric_loader_version=0.19.5
fabric_api_version=0.159.0+26.2
fabric_loom_version=1.17-SNAPSHOT
